# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
# https://qiita.com/hondakaggle/items/7b8984f1190538cb4b3d
# https://deepage.net/features/numpy-reshape.html

In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)
np.show_config()

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/YamamotoK/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/YamamotoK/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/YamamotoK/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/YamamotoK/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/YamamotoK/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/YamamotoK/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/YamamotoK/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/YamamotoK/Anaconda3\\Library\\include']


#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [8]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [18]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [25]:
Z = np.arange(50)
print(Z)
print(Z[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
Z = np.arange(9)
Z = np.reshape(Z,(3,3))
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [18]:
Z = np.array([1,2,0,0,4,0])
print(Z[Z==0])

nz = np.nonzero([1,2,0,0,4,0])
print(nz)

[0 0 0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [30]:
# Z = np.eye(3,3) #正方行列じゃないとき
Z = np.identity(3) #正方行列の時
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [57]:
Z = np.random.randn(3,3,3)
print(Z)

[[[-0.41314131  0.73451427 -0.32888797]
  [ 0.17282167  0.53044039 -0.03126537]
  [ 0.32851528 -1.34517279 -1.31248898]]

 [[-0.63686359 -1.4130211  -0.23544206]
  [-1.17598823 -0.46194199 -1.32692829]
  [ 0.44650883  1.90868816 -0.87179255]]

 [[-1.54399786 -0.51477791  0.85262793]
  [-1.27393071  0.65983642 -0.84110278]
  [ 0.70988033 -1.28973387  1.61973152]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [60]:
Z = np.random.randn(10,10)
print(Z)
Z = np.amax(Z)
print(Z)

[[-0.43754832  0.71056106 -1.10861752  0.0493246  -0.01595656 -0.98668619
  -1.3676131   2.03311295  1.25753839  0.76316044]
 [ 1.16418917  0.45341348 -0.40872583 -1.30706024 -0.8978732   0.6623245
  -0.73309207  0.68751551 -0.641974   -1.0106719 ]
 [-0.85591419 -0.17192552  0.75580281 -0.83108032 -0.22422375  0.84509958
   1.29223892 -0.40510358  0.23950134  0.56530511]
 [ 1.02392801 -0.27120789 -0.08327664  0.8219621   0.43858093 -1.39081371
   0.49151155 -0.03528452 -0.22230522 -1.7881223 ]
 [-0.02674954 -0.89974144 -0.87947939 -2.08099753  1.12164645  0.17920381
  -0.71333443  0.35142278 -1.35523726  1.21271116]
 [-0.95007621 -1.38238304 -0.09349572 -1.1001445   0.46925425 -0.45883829
   0.49259149 -0.36097712  0.03725769  0.98083763]
 [-0.43838873  0.69169642 -0.6787601   0.16028789 -1.304936    0.27318149
  -2.41748281  1.94616548 -0.40047851 -0.21360572]
 [ 0.39739586  0.02498594  0.49489489  0.65056161  0.94901305  1.54275989
   0.14404056  0.67598888  0.74842152 -0.58122788]
 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [62]:
Z = np.random.randn(30)
print(Z)
Z = np.average(Z)
print(Z)
answer(14)

[-1.31538901  0.7991358  -0.14883527 -0.20085688  1.5222172   1.34411717
  1.39041292 -0.9826705  -1.19794367  0.96875326 -0.91352905  0.15989157
  0.14545678  0.49615383  0.26089866  0.90497128 -0.78152721 -1.35534562
 -0.3800172   0.00793835  0.39461836 -0.44955527  0.51145763 -1.34505812
 -0.67776934  0.23995121  0.36521477 -1.8829049   1.97542531  0.85808687]
0.023776631012758988
Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [71]:
# hint(15)
# answer(15)
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)
# [X:-A, Y:-B]
# X:行列の行のスタートとなる値
# A:行列の行のエンドとなる値。マイナス値の場合は、最後から数えた値になる。
# Y:行列の列のスタートとなる値
# B:行列の列のエンドとなる値。マイナス値の場合は、最後から数えた値になる。
# 配列の大きさに依存しなくなる

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [80]:
Z = np.random.randn(4,4)
Z = np.pad(Z,1)
print(Z)

[[ 0.          0.          0.          0.          0.          0.        ]
 [ 0.         -1.77479085  0.62294642  1.42484174  0.62763176  0.        ]
 [ 0.          1.65020925 -0.59980379 -0.86433517  0.86561599  0.        ]
 [ 0.         -0.53691491  0.56042092  1.39684309 -0.37265013  0.        ]
 [ 0.         -0.22318974  0.4018832  -0.69528318  1.42555554  0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [92]:
0 * np.nan #nan
# np.nan == np.nan #False
# np.inf > np.nan #False
# np.nan - np.nan #nan
# np.nan in set([np.nan]) #True
# 0.3 == 3 * 0.1 #False

Object `in` not found.


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [104]:
# hint(18)
answer(18)
Z = np.arange(1,5)
print(Z)
Z = np.diag(Z,k=-1)
print(Z)

Z = np.diag(1+np.arange(4),k=-1)
print(Z)
[1 2 3 4]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [121]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)
# https://note.nkmk.me/python-numpy-ndarray-slice/

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [129]:
Z = np.array?
Z = np.unravel_index?
# hint(20)
answer(20)

print(np.unravel_index(99,(6,7,8)))


In [134]:
Z = np.array((6,7,8))
Z = np.unravel_index(99,Z)
print(Z)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [148]:
Z = np.array([[1,0],[0,1]])
print(Z)
Z = np.tile(Z,(4,4))
print(Z)
# answer(21)

[[1 0]
 [0 1]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [156]:
Z = np.random.randn(5,5)
Z_ave = np.average(Z)
Z_std = np.std(Z)

print((Z-Z_ave)/Z_std)
# answer(22)

[[ 0.19716839  1.20898048 -2.02914413  0.4003199   1.00217915]
 [ 0.32226481 -1.59172699  0.49443617 -0.65769932  0.82181502]
 [ 0.21635195 -0.7612012  -0.14517785 -1.20082936  0.56910837]
 [ 0.30476164  0.20632452  0.27398479 -2.19337508 -0.12429016]
 [ 0.65462718 -1.45787296  1.43904024  1.18561705  0.86433739]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [159]:
color = np.dtype?

In [ ]:
color = np.dtype(([('R',np.ubyte),
                   ('G',np.ubyte),
                   ('B',np.ubyte),
                   ('A',np.ubyte),]))

In [160]:
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [170]:
a = np.random.randint(0,10,(5,3))
b = np.random.randint(0,10,(3,2))
# print(a)
# print(b)
print(np.dot(a,b))
answer(24)

[[21 21]
 [43 31]
 [68 56]
 [75 57]
 [43 40]]
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [173]:
# hint(25)
# answer(25)
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1 #Trueのところに-つける
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [183]:
print(sum(range(5),-1))
# range():0から任意の値までの連番
# https://note.nkmk.me/python-range-usage/
# sum(A,B):Aの合計にBを加算
# from numpy import *
# print(sum(range(5),-1))
answer(26)

10
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [214]:
Z = np.ones((2,3))
Z *= 2
print(Z)
print(Z<Z)

[[2. 2. 2.]
 [2. 2. 2.]]
[[False False False]
 [False False False]]


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [218]:
# print(np.array(0) / np.array(0))#エラー
# print(np.array(0) // np.array(0))#エラー
print(np.array([np.nan]).astype(int).astype(float))#めちゃ少数-2.14748365e+09

[-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆)

In [244]:
# Z = np.random.random((2,3))
# print(Z)
# print(np.round(Z))
# answer(29)
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-1.  6.  3.  8. -4.  5. -1.  2.  3. -9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [246]:
a,b = np.array([1,2,2,2]),np.array([1,3,3,3])
print(np.intersect1d(a,b))
answer(30)

[1]
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [254]:
np.errstate(divide='ignore')
np.seterr(all='ignore')
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [258]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
# sqrt:平方根
# これは実数しか表示できないからロードが終わらなくなる
# emath:複素数
# np.sqrt(-1)はnanになり、np.emath.sqrt(-1)は1jになります。
# ここで、jは複素数を表す記号です。np.emathは複素数を扱うときに使うようですが、emathが何の略かはわかりませんでした。

False


<ipython-input-258-4720da0c995e>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [268]:
# hint(33)
# answer(33)
yesterday = np.datetime64('today') - np.timedelta64(1)
print(yesterday)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
# 下のほうが便利

# import datetime
# today = datetime.datetime.today()

# print(today)  # 2019-11-26 14:49:47.623516
# print(type(today))  # <class 'datetime.datetime'>

# tomorrow = today + datetime.timedelta(days=1)
# yesterday = today - datetime.timedelta(days=1)

# print(tomorrow)  # 2019-11-27 14:49:47.623516
# print(yesterday)  # 2019-11-25 14:49:47.623516

# print(type(tomorrow))  # <class 'datetime.datetime'>

2021-05-27 15:57:35.237762
<class 'datetime.datetime'>
2021-05-28 15:57:35.237762
2021-05-26 15:57:35.237762
<class 'datetime.datetime'>


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [271]:
# hint(34)
# answer(34)
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [292]:
# hint(35)
answer(35)
A = np.arange(3)
B = np.arange(2,5)
np.add(A,B,out=B)
np.divide(A,2,A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


TypeError: No loop matching the specified signature and casting was found for ufunc true_divide

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [320]:
print(np.random.randint(3,10,(2,3)))#整数でランダム出力
Z = 10 * np.random.rand(2,3)
# Z = np.round(Z)#四捨五入
# Z = np.floor(Z)#切り捨て
# Z = np.ceil(Z)#切り上げ
# print(Z.astype(int))#型変換
print(Z)
# hint(36)
answer(36)

[[5 7 6]
 [4 8 7]]
[[6.36519034 3.91469365 1.72401796]
 [6.22717859 5.80777646 1.87942389]]
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [322]:
print(np.random.randint(0,4,(5,5)))
print(np.arange)

[[1 2 0 3 1]
 [0 3 1 1 2]
 [1 0 2 2 3]
 [2 3 1 1 1]
 [3 2 2 2 3]]
hint: np.arange


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [6]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [3]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)
# hint(39)
answer(39)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [9]:
Z = np.random.randn(10)
Z = np.sort(Z)
print(Z)
# answer(40)

[-2.56099841 -2.39530501 -1.98191575 -1.76781658 -0.682416    0.10628152
  0.21439495  0.52855008  0.67706171  1.01735301]
Z = np.random.random(10)
Z.sort()
print(Z)


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [12]:
hint(41)
# https://www.randpy.tokyo/entry/numpy_ufunc
Z = np.arange(10)
print(np.add.reduce(Z))

hint: np.add.reduce
45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [17]:
A = np.arange(3)
B = np.arange(3)
np.all(A==B)
# answer(42)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

True
True


#### 43. Make an array immutable (read-only) (★★☆)

In [24]:
A = np.arange(3)
# A.flags.writeable = False
A.setflags(write=False)#上下どっちでもOK
A[0]=1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [36]:
# 配列生成
x = np.random.randint(0,10,(10,2))
y = np.random.randint(0,10,(10,2))
    
#     # 直交座標系 → 極座標系
radii = np.sqrt(x**2 + y**2)
theta = np.arctan2(y,x)


Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)
answer(44)

[0.99057424 0.7961811  0.52995073 1.19750332 0.60790561 0.44172959
 1.30307188 0.35602435 0.93991982 0.80549116]
[0.0045562  0.2747624  0.28929047 0.94062393 0.01551458 1.13684462
 0.84077123 0.31717771 0.33547496 0.71166644]
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [53]:
Z = np.random.random(10)
Z[np.argmax(Z)] = 0
print(Z)
answer(45)
# np.argmax?

[0.38559532 0.20819462 0.42168833 0.82247418 0.33748163 0.6869429
 0.2740388  0.37361704 0.         0.07628525]
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [55]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [60]:

answer(47)

# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


In [63]:
X = np.random.randn(4)
Y = np.random.rand(4)
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

1.2861111230655903e-06


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [72]:
answer(48)

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


In [74]:
Z = np.iinfo(np.int64)#iinfo:intのinfoの略
A = np.finfo(np.float64)#finfo:floatのinfoの略
print(Z.min)
print(A.min)
print(Z.max)
print(A.max)

-9223372036854775808
-1.7976931348623157e+308
9223372036854775807
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [85]:
# Z = np.random.rand(3,4)
# answer(49)
np.set_printoptions(threshold=float("inf"))
Z = np.random.randn(10)
print(Z)

[-0.57768241  0.12330929 -0.13309271 -0.91425201  1.59596503  0.47137081
  0.1066467  -0.13443489 -0.14998715  0.37766249]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [231]:
T = 3
Y = 4

Z = np.random.randn(T,Y)
Z = np.reshape(Z,(1,(T*Y)))
ind = np.abs(Z-0.5)
print(ind)
ind = np.argmin(ind)
print(ind)
print(Z[0,ind])
# answer(50)

[[1.06167708 1.19626611 1.29373607 0.02270464 0.39888569 0.22520353
  0.68751981 0.09084536 1.23787686 0.84656771 0.21615926 0.66069285]]
3
0.47729536095525293


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)