In [1]:
# coding: utf-8
import sys
sys.path.append('..') 
from common.np import *  # import numpy as np
from common.config import GPU
from common.functions import softmax, cross_entropy_error

In [1]:
# coding: utf-8
import numpy as np


class Sigmoid:
    def __init__(self):
        self.params = []

    def forward(self, x):
        return 1 / (1 + np.exp(-x))


class Affine:
    def __init__(self, W, b):
        self.params = [W, b]

    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out


class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        # 重みとバイアスの初期化
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        # レイヤの生成
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        # すべての重みをリストにまとめる
        self.params = []
        for layer in self.layers:
            self.params += layer.params

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x


x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)
print(s)

[[-0.43355132 -2.47144666  0.37591431]
 [-0.84516072 -3.42688208  1.75801827]
 [-0.67276707 -2.65768252  0.38097704]
 [ 0.18634862 -3.23943033  1.72160331]
 [-0.80871328 -2.72307225  0.3658284 ]
 [-0.9154697  -2.05638799 -0.2891742 ]
 [ 0.02039839 -2.72937289  0.94943429]
 [-0.30660858 -3.07833073  1.21541513]
 [ 0.37772186 -2.87579506  1.34977589]
 [ 0.30788064 -2.61843922  1.06468681]]


In [2]:
class MatMul:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None

    def forward(self, x):
        W, = self.params
        out = np.dot(x, W)
        self.x = x
        return out

    def backward(self, dout):
        W, = self.params
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        self.grads[0][...] = dW
        return dx

# https://qiita.com/segavvy/items/91be1d4fc66f7e322f25
# [...]:は深いコピー→片方が値を変更すると両方に反映される